version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: portfolio_website
    volumes:
      - .:/website
    ports:
      - "8000:8000"
    
