# Generated by Django 2.2.1 on 2019-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('end_date',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
