# Generated by Django 2.2.1 on 2019-06-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date__year', '-end_date__month']},
        ),
    ]
